DFP/urls.py
from django.contrib import admin
from django.urls import path
from department import views

urlpatterns = [

    # 部门管理
    path('depart/list/', views.depart_list),
    path('depart/add/', views.depart_add),
    path('depart/delete/', views.depart_delete),
    path('depart/<int:nid>/edit/', views.depart_edit),

    # 职工管理
    path('personnel/list/', views.personnel_list),
    path('personnel/add/', views.personnel_add),
    path('personnel/<int:nid>/edit/', views.personnel_edit),
    path('personnel/<int:nid>/delete/', views.personnel_delete),

    # 登录界面
    path('login/', views.login),
    path('logout/', views.logout),
]

department/models.py
from django.db import models


# Create your models here.

class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)


class Department(models.Model):
    """ 部门表 """
    title = models.CharField(verbose_name='标题', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """ 员工表 """
    name = models.CharField(verbose_name="姓名", max_length=16)
    employee_id = models.CharField(verbose_name="工号", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    salary = models.DecimalField(verbose_name="薪资", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateTimeField(verbose_name="入职时间")

    depart = models.ForeignKey(verbose_name="所属部门", to="Department", to_field="id", on_delete=models.CASCADE)

department/views.py
from django.shortcuts import render, redirect
from department import models
from django import forms
from django.conf import settings
from django.utils.deprecation import MiddlewareMixin
import hashlib


def depart_list(request):
    """ 部门列表 """
    queryset = models.Department.objects.all()
    return render(request, 'depart_list.html', {'queryset': queryset})


def depart_add(request):
    """ 添加部门 """
    if request.method == "GET":
        return render(request, 'depart_add.html')

    title = request.POST.get("title")
    models.Department.objects.create(title=title)

    return redirect("/depart/list")


def depart_delete(request):
    """ 删除部门 """
    nid = request.GET.get('nid')

    models.Department.objects.filter(id=nid).delete()

    return redirect("/depart/list")


def depart_edit(request, nid):
    """ 修改部门 """
    if request.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()

        return render(request, 'depart_edit.html', {"row_object": row_object})

    title = request.POST.get("title")
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/list/")


def personnel_list(request):
    """ 职工管理 """
    queryset = models.UserInfo.objects.all()
    """
    for obj in queryset:
        print(obj.id, obj.name, obj.employee_id, obj.age, obj.depart.title, obj.salary,
              obj.create_time.strftime("%Y-%m-%d"))
    """
    return render(request, 'personnel_list.html', {"queryset": queryset})


class PersonnelModelForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ["name", "employee_id", "depart", "age", "create_time", "salary"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control"}


def personnel_add(request):
    """ 添加职工 """
    if request.method == "GET":
        form = PersonnelModelForm()
        return render(request, 'personnel_add.html', {"form": form})

    form = PersonnelModelForm(data=request.POST)
    if form.is_valid():
        # 数据合法，保存至数据库
        # print(form.cleaned_data)
        form.save()
        return redirect('/personnel/list')

    return render(request, 'personnel_add.html', {"form": form})
    """
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} : {{ field }}
        {% endfor %}
    
    </form>
    """


def personnel_edit(request, nid):
    """ 编辑职工 """

    row_object = models.UserInfo.objects.filter(id=nid).first()

    if request.method == "GET":
        form = PersonnelModelForm(instance=row_object)
        return render(request, 'personnel_edit.html', {"form": form})

    form = PersonnelModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/personnel/list/')
    return render(request, 'personnel_edit.html', {"form": form})


def personnel_delete(request, nid):
    """ 删除职工 """
    models.UserInfo.objects.filter(id=nid).delete()

    return redirect("/personnel/list")


def md5(data_string):
    obj = hashlib.md5(settings.SECRET_KEY.encode('utf-8'))
    obj.update(data_string.encode('utf-8'))
    return obj.hexdigest()


class LoginForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        required=True,
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=True,
    )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # print(form.cleaned_data)
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 生成随机字符串，并写入 cookie 和 session
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        return redirect('/depart/list')
    return render(request, 'login.html', {'form': form})


class AuthMiddleware(MiddlewareMixin):

    def process_request(self, request):
        if request.path_info == "/login/":
            return

        info_dict = request.session.get("info")
        if info_dict:
            return

        return redirect('/login/')


def logout(request):
    """ 注销 """

    request.session.clear()

    return redirect('/login/')









department/templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}

    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> 新建部门 </h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">部门名称</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="填写部门名称" name="title"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">提 交</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

department/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> 修改部门 </h3>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">部门名称</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" placeholder="填写部门名称" name="title"
                                       value="{{ row_object.title }}"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">提 交</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

department/templates/depart_list.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-primary" href="/depart/add/">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    新建部门
                </a>
            </div>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    部门列表
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>部门名称</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in queryset %}
                        <tr>
                            <th scope="row">{{ obj.id }}</th>
                            <td>{{ obj.title }}</td>
                            <td>
                                <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/">编辑</a>
                                <a class="btn btn-danger btn-xs" href="/depart/delete/?nid={{ obj.id }}">删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

department/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>组织架构管理系统</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/depart/list"> 组织架构管理系统 </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list">部门管理</a></li>
                <li><a href="/personnel/list">职工管理</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/logout/">注 销</a></li>
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
{#                       aria-expanded="false">当前用户 <span class="caret"></span></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">个人资料</a></li>#}
{#                        <li><a href="#">我的信息</a></li>#}
{#                        <li role="separator" class="divider"></li>#}
{#                        <li><a href="#">注销</a></li>#}
{#                    </ul>#}
{#                </li>#}
            </ul>
        </div>
    </div>
</nav>

<div>
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

department/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
<style>
    .account {
        width: 400px;
        border: 1px solid #dddddd;
        border-radius: 5px;
        box-shadow: 5px 5px 20px #aaaaaa;

        margin-left: auto;
        margin-right: auto;
        margin-top: 100px;
        padding: 20px 40px;
    }

    .account h2 {
        margin-top: 10px;
        text-align: center;
    }
</style>
</body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color:red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color:red;">{{ form.password.errors.0 }}</span>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>
</html>

department/templates/personnel_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet"
          href="{% static 'plugins/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block content %}

    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> 添加职工 </h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span style="color:red;">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datetimepicker-master/js/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datetimepicker({
                pickTime: false,
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });
        })
    </script>
{% endblock %}

department/templates/personnel_edit.html
{% extends 'layout.html' %}

{% block content %}

    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"> 编辑职工 </h3>
                </div>
                <div class="panel-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                <span style="color:red;">{{ field.errors.0 }}</span>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

department/templates/personnel_list.html
{% extends 'layout.html' %}

{% block content %}

    <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-primary" href="/personnel/add">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    添加职工
                </a>
            </div>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    员工名单
                </div>

                <!-- Table -->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>工号</th>
                        <th>年龄</th>
                        <th>所属部门</th>
                        <th>入职时间</th>
                        <th>薪资</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in queryset %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.employee_id }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.depart.title }}</td>
                        <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                        <td>{{ obj.salary }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/personnel/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/personnel/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}